#### 1. try catch模型
```
try{

}catch(e){
    consloe.log('sfsdf': e);
}
```

#### 2. 异步的捕捉
异步代码不能在外面调用，只能在回调函数内部执行try catch
```
function printTime() {
    throw new Error();
}

try {
    setTimeout(printTime, 1000);
    console.log('done');
} catch (e) {
    alert('error');
}

```

这个是不会catch到错误的，因为会直接执行到结束，throw的时候，已经结束try了

同理
```
try {
    $btn.click(function () {
        var
            x = parseFloat($('#x').val()),
            y = parseFloat($('#y').val()),
            r;
        if (isNaN(x) || isNaN(y)) {
            throw new Error('输入有误');
        }
        r = x + y;
        alert('计算结果：' + r);
    });
} catch (e) {
    alert('输入有误！');
}

```
这个也是直接结束，try不到错误，只能在function里面进行try